port: 12395
dbFile: "data/data.db"
logFile: "logs/share.log"
mediaDir: "media_dir"
# 数据库类型: sqlite, mysql, postgresql
dbType: "sqlite"
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  pass: "postgres"
  dbName: "share"
  sslMode: "disable"
mysql:
  host: "192.168.31.51"
  port: 3306
  user: "root"
  pass: "password"
  dbName: "share"
taskEngine:
  workerCount: 4
  bufferSize: 89120
  processTimeout: 1800
  maxRetry: 3
