import type { App, Component } from 'vue'
import {
  NAlert,
  NBreadcrumb,
  NBreadcrumbItem,
  NButton,
  NButtonGroup,
  NCard,
  NCascader,
  NCheckbox,
  NCode,
  NConfigProvider,
  NDataTable,
  NDatePicker,
  NDescriptions,
  NDescriptionsItem,
  NDialogProvider,
  NDivider,
  NDrawer,
  NDrawerContent,
  NDropdown,
  NDynamicTags,
  NEllipsis,
  NEmpty,
  NForm,
  NFormItem,
  NGlobalStyle,
  NGrid,
  NGridItem,
  NIcon,
  NInput,
  NInputGroup,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NList,
  NListItem,
  NMenu,
  NMessageProvider,
  NModal,
  NModalProvider,
  NNotificationProvider,
  NPagination,
  NPopover,
  NQrCode,
  NRadio,
  NRadioButton,
  NRadioGroup,
  NSelect,
  NSlider,
  NSpace,
  NSpin,
  NSwitch,
  NTab,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NThing,
  NTooltip,
  NTree,
} from 'naive-ui'

const components = [
  NAlert,
  NBreadcrumb,
  NBreadcrumbItem,
  NButton,
  NButtonGroup,
  NCard,
  NCascader,
  NCheckbox,
  NCode,
  NConfigProvider,
  NDataTable,
  NDatePicker,
  NDescriptions,
  NDescriptionsItem,
  NDialogProvider,
  NDivider,
  NDrawer,
  NDrawerContent,
  NDropdown,
  NDynamicTags,
  NEllipsis,
  NEmpty,
  NForm,
  NFormItem,
  NGlobalStyle,
  NGrid,
  NGridItem,
  NIcon,
  NInput,
  NInputGroup,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NList,
  NListItem,
  NMenu,
  NMessageProvider,
  NModal,
  NModalProvider,
  NNotificationProvider,
  NPagination,
  NPopover,
  NQrCode,
  NRadio,
  NRadioButton,
  NRadioGroup,
  NSelect,
  NSlider,
  NSpace,
  NSpin,
  NSwitch,
  NTab,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NThing,
  NTooltip,
  NTree,
] as Component[]

const toKebabCase = (value: string) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()

export const registerNaiveComponents = (app: App) => {
  components.forEach((component) => {
    if (component.name) {
      app.component(component.name, component)
      app.component(`n-${toKebabCase(component.name)}`, component)
    }
  })
}
